### ISSUE TITLE
Events table not configurable 

### ISSUE THREAD

**Issue by wagner-certat** [Intevation/intelmq-fody-backend#16]
https://github.com/Intevation/intelmq-fody-backend/blob/b4992ea/events_api/events_api/serve.py#L399

Could/should be a configurable

**Comment by bernhardreiter** [comment]
Hi @wagner-certat,
out of curiosity: What is the use case for configurating this? Wouldn't be better if most
installations would agree on using "events" here?

**Comment by wagner-certat** [comment]
> Wouldn't it be better if most
installations would agree on using "events" here?

Sure, but is the name of the table really a hard dependency?

In our case I want fody to operate on a view. Otherwise I need to rename the view, then the events table is no longer called events (but you suggest the opposite) :)

**Comment by bernhardreiter** [comment]
No, its not, thanks for mentioning the view use-case, my imagination was not at its highest level in this moment. ;)
