### ISSUE TITLE
Add endpoint to search for `aggregate_identifier`

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody-backend#22]
To be able to allow for https://github.com/Intevation/intelmq-fody/issues/74
an endpoint is needed that provides the ability to search for `aggregate_identifier`.

## Implementation details
As `aggregate_identifier` is a column in the table `directives` of the event database, the module `tickets_api` is a candidate as it already accesses the database and the table in question.

However we need to filter possibility for events and fody is using the `events_api` module for this filtering.

**Comment by bernhardreiter** [comment]
Fixed with 147e94c375ee5dab38dabb487f0bb5078ee8689a.

**Comment by bernhardreiter** [comment]
The current implementation of this feature makes it mandatory to have the intelmq-cb-mailgen tables in the result database. The may be an obstacle for other users of the events backend.

**Comment by bernhardreiter** [comment]
e73c088944e66afb821a128acf5ea166d0467c6b keeps the ability to run without extra mailgen tables.

**Comment by wagner-certat** [comment]
> @wagner-certat BTW: Do you use the events module and fody with a plain postgresql output table somewhere?

Yes, we do, but requiring additional empty tables is reasonable IMO.

> Any details you can share?

Well, we have an instance of https://github.com/certat/intelmq-fody / https://github.com/certat/intelmq-fody-backend (branches fody-dev / staging) running internally as an interface for the eventdb but without mailgen. The fork has some adapations and extensions which I am trying to get upstream step by step - but slowly.

**Comment by bernhardreiter** [comment]
@wagner-certat thanks for your response.

The current version has a check of the extra tables exist and add additional support only if they do, so your usecase should be fully supported. :)

**Comment by bernhardreiter** [comment]
The current implementation needs additional fixes
 *  as joining of the tables leads to more fields in the results and the field `notification_interval` is of type `timedelta` which leads to an error if serialised with hug v2.2.0. 
 * the display in fody is getting confusing if the table columns from the three tables mix.

**Comment by bernhardreiter** [comment]
== Development
If there is an event with id 452 in the database and you have taken care
of the authentification, here are three simple tests for the three endpoints affected from
the joning tables and serialisation problem:
```sh
curl http://localhost:8070/api/events\?id=452
curl http://localhost:8070/api/events/export\?id=452
curl http://localhost:8070/api/events/search\?id=452

**Comment by bernhardreiter** [comment]
72284fd6875177d85f8009fd88daa4429592f6d5 allows for clients to see the mailgen tables better in the result object as they are seperated fields now.
