### ISSUE TITLE
events: remove unused /export endpoint

### ISSUE THREAD

**Issue by bernhardreiter** [Intevation/intelmq-fody-backend#24]
The `./export` endpoint for the **events** seems superfluous as it is not used by fody
and it is very similar to `/search`.

Does somebody use this endpoint?

**Comment by wagner-certat** [comment]
We don't use it (just /search).

**Comment by th-certbund** [comment]
> We don't use it (just /search).

Same with us.

**Comment by bernhardreiter** [comment]
@wagner-certat @th-certbund thanks for your feedback.
-> We'll remove the endpoint in the next revision.

**Comment by bernhardreiter** [comment]
removed with b86f51d12997ee73c4366cd3278f1c272e066187
