### ISSUE TITLE
No module named 'checkticket_api.checkticket_api' leading to 404 error API - wsgi 

### ISSUE THREAD

**Issue by kodebrain** [Intevation/intelmq-fody-backend#34]
####  Snippet of the error from Fody
`
Error 404: { "404": "The API call you tried to make was not defined. Here's a definition of the API to help you get going :)", "documentation": { "overview": "Provides an API for IntelMQ\n\nRequires hug (http://www.hug.rest/)\n\nDevelopment: call like\n hug -f serve.py\n connect to http://localhost:8000/\n\nSeveral configuration methods are shown within the code.\n\n\nCopyright (C) 2016, 2017 by Bundesamt für Sicherheit in der Informationstechnik\n\nSoftware engineering by Intevation GmbH\n\nThis program is Free Software: you can redistribute it and/or modify\nit under the terms of the GNU Affero General Public License as published by\nthe Free Software Foundation, either version 3 of the License, or\n(at your option) any later version.\n\nThis program is distributed in the hope that it will be useful,\nbut WITHOUT ANY WARRANTY; without even the implied warranty of\nMERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\nGNU Affero General Public License for more details.\n\nYou should have received a copy of the GNU Affero General Public License\nalong with this program. If not, see <http://www.gnu.org/licenses/>.\n\nAuthor(s):\n * Bernhard E. Reiter <bernhard@intevation.de>\n * Dustin Demuth <dustin@intevation.de>\n", "handlers": { "/api/contactdb/ping": { "GET": { "examples": [ "http://192.168.0.1:8000/api/contactdb/ping" ], "requires": [ null ], "outputs": { "format": "JSON (Javascript Serialized Object Notation)", "content_type": "application/json; charset=utf-8" } } }, "/api/contactdb/searchasn": { "GET": { "requires": [ null ], "outputs": { "format": "JSON (Javascript Serialized Object Notation)", "content_type": "application/json; charset=utf-8" }, "inputs": { "asn": { "type": "Integer" } } } }, "/api/contactdb/searchorg": { "GET": { "usage": "Search for an entry with the given name.\n\n Search is an case-insensitive substring search.\n ", "requires": [ null ], "outputs": { "format": "JSON (Javascript Serialized Object Notation)", "content_type": "application/json; charset=utf-8" }, "inputs": { "name": { "type": "String" } } } }, "/api/contactdb/searchcontact": { "GET": { "usage": "Search for an entry with the given email address.\n\n Uses a case-insensitive substring search.\n ", "requires": [ null ], "outputs": { "format": "JSON (Javascript Serialized Object Notation)", "content_type": "application/json; charset=utf-8" }, "inputs": { "email": { "type": "String" } } } }, "/api/contactdb/searchdisabledcontact": { "GET": { "usage": "Search for entries where string is part of a disabled email address.\n\n Uses a case-insensitive substring search.\n ", "requires": [ null ], "outputs": { "format": "JSON (Javascript Serialized Object Notation)",} } } } `

#### apache error log for fody-backend-error.log

```
[Thu Mar 02 12:29:55.963308 2023] [wsgi:error] [pid 7323:tid 140471292634688] [client 127.0.0.1:48880] 2023-03-02 12:29:55,963 tickets_api.tickets_api.serve INFO - b'SELECT date_trunc(\\'hour\\', "sent_at"), count(distinct(intelmq_ticket))  FROM events  JOIN directives on directives.events_id = events.id  JOIN sent on sent.id = directives.sent_id  WHERE sent."sent_at" > \\'2023-03-02T00:00:00\\'::timestamp AND sent."sent_at" < \\'2023-03-03T00:00:00\\'::timestamp GROUP BY date_trunc(\\'hour\\', "sent_at")', referer: http://192.168.0.1:8000/
[Thu Mar 02 12:29:55.965209 2023] [wsgi:error] [pid 7323:tid 140471301027392] [client 127.0.0.1:48898] 2023-03-02 12:29:55,964 events_api.events_api.serve INFO - b'SELECT date_trunc(\\'hour\\', "time.observation"), count(DISTINCT events.id) FROM events\\n                LEFT OUTER JOIN directives\\n                             ON directives.events_id = events.id LEFT OUTER JOIN sent ON sent.id = directives.sent_id WHERE events."time.observation" > \\'2023-03-02T00:00:00\\'::timestamp AND events."time.observation" < \\'2023-03-03T00:00:00\\'::timestamp GROUP BY date_trunc(\\'hour\\', "time.observation") ORDER BY date_trunc', referer: http://192.168.0.18000/
[Thu Mar 02 12:35:18.163571 2023] [wsgi:error] [pid 7322:tid 140471334598208] [client 127.0.0.1:35266] 2023-03-02 12:35:18,163 contactdb_api.contactdb_api.serve DDEBUG - Ran query="\\n        SELECT tag_name,\\n               json_object_agg(tag_value,\\n                               CASE WHEN tag_description = '' THEN tag_value\\n                                    ELSE tag_description\\n                               END) AS tags,\\n               coalesce(min(tag_value) FILTER (WHERE is_default), '')\\n               AS default_tag\\n          FROM tag_name JOIN tag ON tag.tag_name_id = tag_name.tag_name_id\\n      GROUP BY tag_name, tag_name_order\\n      ORDER BY tag_name_order", referer: http://192.168.0.1:8000/contacts
[Thu Mar 02 12:35:19.942594 2023] [wsgi:error] [pid 7322:tid 140471326205504] [client 127.0.0.1:35266] 2023-03-02 12:35:19,942 tickets_api.tickets_api.serve INFO - b'SELECT date_trunc(\\'hour\\', "sent_at"), count(distinct(intelmq_ticket))  FROM events  JOIN directives on directives.events_id = events.id  JOIN sent on sent.id = directives.sent_id  WHERE sent."sent_at" > \\'2023-03-02T00:00:00\\'::timestamp AND sent."sent_at" < \\'2023-03-03T00:00:00\\'::timestamp GROUP BY date_trunc(\\'hour\\', "sent_at")', referer: http://192.168.0.1:8000/
[Thu Mar 02 12:35:19.944364 2023] [wsgi:error] [pid 7322:tid 140471301027392] [client 127.0.0.1:35284] 2023-03-02 12:35:19,944 events_api.events_api.serve INFO - b'SELECT date_trunc(\\'hour\\', "time.observation"), count(DISTINCT events.id) FROM events\\n                LEFT OUTER JOIN directives\\n                             ON directives.events_id = events.id LEFT OUTER JOIN sent ON sent.id = directives.sent_id WHERE events."time.observation" > \\'2023-03-02T00:00:00\\'::timestamp AND events."time.observation" < \\'2023-03-03T00:00:00\\'::timestamp GROUP BY date_trunc(\\'hour\\', "time.observation") ORDER BY date_trunc', referer: http://192.168.0.1:8000/
```
```
/usr/local/lib/python3.10/dist-packages/intelmq_fody_backend-0.9.2-py3.10.egg/intelmq_fody_backend
hug -f serve.py -p 8003
2023-03-02 12:50:41,492 serve DEBUG - prepare session config
Loading config from /etc/intelmq/fody-session.conf
2023-03-02 12:50:41,510 serve WARNING - No module named 'checkticket_api.checkticket_api'
sys:1: DeprecatedWarning: Call to deprecated function __init__(...). API class may be removed in a future release, use falcon.App instead.
2023-03-02 12:50:42,565 contactdb_api.contactdb_api.serve DEBUG - Initialised DB connection for contactdb_api.
2023-03-02 12:50:42,643 serve DEBUG - None

/#######################################################################\
          `.----``..-------..``.----.
         :/:::::--:---------:--::::://.
        .+::::----##/-/oo+:-##----:::://
        `//::-------/oosoo-------::://.       ##    ##  ##    ##    #####
          .-:------./++o/o-.------::-`   ```  ##    ##  ##    ##  ##
             `----.-./+o+:..----.     `.:///. ########  ##    ## ##
   ```        `----.-::::::------  `.-:::://. ##    ##  ##    ## ##   ####
  ://::--.``` -:``...-----...` `:--::::::-.`  ##    ##  ##   ##   ##    ##
  :/:::::::::-:-     `````      .:::::-.`     ##    ##    ####     ######
   ``.--:::::::.                .:::.`
         ``..::.                .::         EMBRACE THE APIs OF THE FUTURE
             ::-                .:-
             -::`               ::-                   VERSION 2.6.0
             `::-              -::`
              -::-`           -::-
\########################################################################/

 Copyright (C) 2016 Timothy Edmund Crosley
 Under the MIT License


Serving on :8003...
```
```
/usr/local/lib/python3.10/dist-packages/intelmq_fody_backend-0.9.2-py3.10.egg/checkticket_api/checkticket_api$ hug -f serve.py -p 8002
sys:1: DeprecatedWarning: Call to deprecated function __init__(...). API class may be removed in a future release, use falcon.App instead.

/#######################################################################\
          `.----``..-------..``.----.
         :/:::::--:---------:--::::://.
        .+::::----##/-/oo+:-##----:::://
        `//::-------/oosoo-------::://.       ##    ##  ##    ##    #####
          .-:------./++o/o-.------::-`   ```  ##    ##  ##    ##  ##
             `----.-./+o+:..----.     `.:///. ########  ##    ## ##
   ```        `----.-::::::------  `.-:::://. ##    ##  ##    ## ##   ####
  ://::--.``` -:``...-----...` `:--::::::-.`  ##    ##  ##   ##   ##    ##
  :/:::::::::-:-     `````      .:::::-.`     ##    ##    ####     ######
   ``.--:::::::.                .:::.`
         ``..::.                .::         EMBRACE THE APIs OF THE FUTURE
             ::-                .:-
             -::`               ::-                   VERSION 2.6.0
             `::-              -::`
              -::-`           -::-
\########################################################################/

 Copyright (C) 2016 Timothy Edmund Crosley
 Under the MIT License


Serving on :8002...

```
Events are generated from postgres to fody. db permissions looks to be right

**Comment by bernhardreiter** [comment]
> ####  Snippet of the error from Fody
> Error 404: { "404": "The API call you tried to make was not defined. 

Which URL gave this reponse (can be seen in the developer infos of the 
browser, networking)?

> 2023-03-02 12:50:41,510 serve WARNING - No module named
> 'checkticket_api.checkticket_api'

^^ looks suspicious.

**Comment by kodebrain** [comment]
```
host
	192.168.0.1:8000
filename
	/api/checkticket/getLastTicketNumber
Address
	192.168.0.1:8000
Status
404
Not Found
VersionHTTP/1.1
Transferred20.27 kB (20.05 kB size)
Referrer Policystrict-origin-when-cross-origin

GET /api/checkticket/getLastTicketNumber HTTP/1.1
Host: 192.168.0.1:8000
User-Agent: Mozilla/5.0 (X11; redacted; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Authorization: 7e681086163778f64f7f3e3d985c55a1
X-Requested-With: XMLHttpRequest
Connection: keep-alive
Referer: http://192.168.0.1:8000/ ```

GET /api/checkticket/getLastTicketNumber HTTP/1.1
Host: 192.168.0.1:8000
User-Agent: Mozilla/5.0 (X11; redacted; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Authorization: 7e681086163778f64f7f3e3d985c55a1
X-Requested-With: XMLHttpRequest
Connection: keep-alive
Referer: http://192.168.0.1:8000/tickets

**Comment by bernhardreiter** [comment]
> GET /api/checkticket/getLastTicketNumber 

Ok, this confirms that the warning

> serve WARNING - No module named 'checkticket_api.checkticket_api'

is likely to cause this problem and shall be investigated.

**Comment by bernhardreiter** [comment]
You may have started the top level hug in the wrong directory which leads to a different PYTHONPATH. Try it like in the Readme.

You had:
> /usr/local/lib/python3.10/dist-packages/intelmq_fody_backend-0.9.2-py3.10.egg/intelmq_fody_backend
> hug -f serve.py -p 8003

Go one up and do:
```bash
hug -f intelmq_fody_backend/serve.py -p 8003
```

**Comment by kodebrain** [comment]
I'm fairly new to fody. The issues that I come across are varied and sometimes it works and I agree that it is due to the packages missing or I'm not running it from the correct directory. 
Would you be able to provide with a detailed step-by-step guide on how to install it on Ubuntu? I would appreciate if that can include all the required dependencies, configuration steps and troubleshooting steps that may help. Thank you
for example:
git clone https://github.com/Intevation/intelmq-fody
git clone https://github.com/Intevation/intelmq-fody-backend
git clone https://github.com/intevation/intelmq-mailgen

Navigate to the directory containing setup.py and run python3 setup.py install ?

My intention is to run fody/fody-backend on a single instance which would then communicate to a sql box that is runing on virtual instance.

**Comment by kodebrain** [comment]
I did a fresh install and it appears everything is working now. 
Few of the errors that I encountered was due to db issue where the  reference was missing the events relation. This was due to the wrong db defined in the tickets-serve.conf
```
2023-03-05 11:29:58,999 tickets_api.tickets_api.serve ERROR - relation "events" does not exist, referer: http://192.168.0.1:8000/
[Sun Mar 05 11:29:58.999411 2023] [wsgi:error] [pid 4572:tid 140096388982336] [client 127.0.0.1:45680] LINE 1: ..."sent_at"), count(distinct(intelmq_ticket))  FROM events  JO..., referer: http://192.168.0.1:8000/
[Sun Mar 05 11:29:58.999417 2023] [wsgi:error] [pid 4572:tid 140096388982336] [client 127.0.0.1:45680]                                                              ^, referer: http://192.168.0.1:8000/
[Sun Mar 05 11:29:58.999564 2023] [wsgi:error] [pid 4572:tid 140096388982336] [client 127.0.0.1:45680] , referer: http://192.168.0.1:8000/
[Sun Mar 05 11:29:58.999655 2023] [wsgi:error] [pid 4572:tid 140096388982336] [client 127.0.0.1:45680] 2023-03-05 11:29:58,999 tickets_api.tickets_api.serve DDEBUG - Calling rollback(), referer: http://192.168.0.1:8000/
[Sun Mar 05 11:29:59.001805 2023] [wsgi:error] [pid 4572:tid 140096196048448] [client 127.0.0.1:45686] 2023-03-05 11:29:59,001 events_api.events_api.serve DDEBUG - Ran query='SELECT date_trunc(\\'hour\\', "time.observation"), count(DISTINCT events.id) FROM events\\n                LEFT OUTER JOIN directives\\n                             ON directives.events_id = events.id LEFT OUTER JOIN sent ON sent.id = directives.sent_id WHERE events."time.observation" > \\'2023-03-05T00:00:00\\'::timestamp AND events."time.observation" < \\'2023-03-06T00:00:00\\'::timestamp GROUP BY date_trunc(\\'hour\\', "time.observation") ORDER BY date_trunc', referer: http://192.168.0.1:8000/

**Comment by bernhardreiter** [comment]
> Would you be able to provide with a detailed step-by-step guide on how to install it on Ubuntu?

In principle our documentation should document everything, but it is aimed at someone with some python administration experience. If you find defects in our documentation, we appreciate specific issues and improvement suggestions.

> did a fresh install and it appears everything is working now.

Cool! Let us know how you like fody. :)
