### ISSUE TITLE
Also rename module intelmq_fody_api to intelmq_fody_backend

### ISSUE THREAD

**Issue by dmth** [Intevation/intelmq-fody-backend#4]
The repository and the package have been renamed to intelmq-fody-backend. Conesequently its reasonable to rename the module `intelmq_fody_api`, too.

- [ ] Rename the directory from intelmq_fody_api to intelmq_fody_backend
- [ ] Adapt the file `setup.py`, accordingly.

**Comment by bernhardreiter** [comment]
With 0ea5af0fb7fbf5a9fbdf6874ecc80917cd9b0f0b and then released with v0.5.0 the module was renamed.
